---
# tasks file for roles/prometheus_host

- name: Installing | Nginx
  apt:
    name: nginx
    state: latest
    update_cache: yes

- name: Starting | Nginx Service
  service:
    name: nginx
    state: started


- name: Installing | Prometheus
  apt:
    name: prometheus
    state: latest
    update_cache: yes

- name: Starting Prometheus
  service:
    name: prometheus
    state: started
    enabled: yes

