#Main

prelim_exam: https://github.com/qjaaferrer/sysad2-12021.git
username: qjaaferrer

#Config_FTP

writable_chroot: allow_writeable_chroot=YES
ftp_config: "allow_writeable_chroot=YES\npasv_min_port=3000\npasv_max_port=31000\nuserlist_file=/etc/vsftp/user_list\nuserlist_deny=NO"

ftp_debian: "pasv_enable=Yes\npasv_min_port=10000\npasv_max_port=10100\nallow_writeable_chroot=YES\nssl_tlsv1\nssl_sslv2=NO\nssl_sslv3=NO"

user: ftpadmin
ftp_pass: $5$f4do2c/U0ZtdxQ$k.xEgEhNK/xO4St1a1oVbBDEkyF/VVBrrYi8WqH9a6C

nagiosuser_pass: $5$Pm/AD6AQPY7$LiWITsucki3K799sm.09CoQbpeBOjNI27yF9uZjVlYEB
nagiosadmin_pass: 123viray
