---
# tasks file for roles/elk_ubuntu 

- name: Installing | Docker
  apt:
    name: docker.io
    state: latest
    update_cache: yes
  register: docker

- name: Install docker.py
  pip:
    name: docker.py
    state: latest
  when: docker.changed

- name: Elastic Search Image | Pulling
  docker_image:
    name: docker.elastic.co/elasticsearch/elasticsearch:7.10.1

- name: Creating | Docker Network
  docker_network:
    name: elastic

- name: Creating | Elastic Container
  docker_container:
    name: elasticsearch
    state: present
    image: docker.elastic.co/elasticsearch/elasticsearch:7.10.1
    ports:
      - "9200:9200"
      - "9300:9300"
    networks:
      - name: elastic

- name: Kibana Image | Pulling
  docker_image:
    name: docker.elastic.co/kibana/kibana:7.10.1

- name: Creating | Kibana Container
  docker_container:
    name: kibana
    image: docker.elastic.co/kibana/kibana:7.10.1
    state: present
    ports:
      - "5601:5601"
    networks:
      - name: elastic

- name: Logstash Image | Pulling
  docker_image:
    name: docker.elastic.co/logstash/logstash:7.10.1

- name: Creating | Logstash Container
  docker_container:
    name: logstash
    image: docker.elastic.co/logstash/logstash:7.10.1
    ports:
      - "5044:5044"
    networks:
      - name: elastic
